apiVersion: v1
kind: Namespace
metadata:
  name: summariser
  labels:
    app.kubernetes.io/part-of: video-summariser
---
apiVersion: v1
kind: Namespace
metadata:
  name: llmgw
  labels:
    app.kubernetes.io/part-of: video-summariser
